name: 360T7-padavanonly-mini

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      device:
        description: 'Target device'
        required: true
        default: 'honor_fur-602'
        type: choice
        options:
          - honor_fur-602
          - abt_asr3000
          - cetron_ct3003
          - cmcc_a10
          - cmcc_rax3000m-emmc-usboffload
          - cmcc_rax3000m-usboffload
          - h3c_nx30pro
          - imou_lc-hx3001
          - jcg_q30
          - konka_komi-a31
          - livinet_zr-3020
          - mt7981-360-t7-108M
          - mt7981-clt-r30b1
          - mt7981-clt-r30b1-112M
          - xiaomi_mi-router-ax3000t
          - xiaomi_mi-router-ax3000t-stock
          - xiaomi_mi-router-wr30u-112m
          - xiaomi_mi-router-wr30u-stock
          - ALL
      clean:
         description: 'clean ccache'
         default: 'false'

  schedule:
    - cron: '0 17 * * 1'

env:
  REPO_URL: https://github.com/bbb0bbb0bbb/immortalwrt-mt798x-24.10
  REPO_BRANCH: 2410
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ./doc/config/mt7981-ax3000-mtwifi-cfg.config
  DIY_P1_SH: ./doc/diy/diy-360T7-hanwckf-1.sh
  DIY_P2_SH: ./doc/diy/diy-360T7-padavanonly-2.sh
  TZ: Asia/Shanghai
  DEVICE: ${{ github.event.inputs.device || 'honor_fur-602' }}
  
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Prepare environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
         sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
         sudo timedatectl set-timezone "$TZ"
         sudo mkdir -p /workdir
         sudo chown "$USER":"$(id -gn)" /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
         df -hT $PWD
         git clone $REPO_URL -b $REPO_BRANCH openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
    
    - name: Cache
      uses: klever1988/cachewrtbuild@main
      with:
         ccache: 'true'
         mixkey: '360T7-padavanonly'
         toolchain: 'true'
         skip: 'true'
         clean: ${{ github.event.inputs.clean || 'false' }}
         prefix: ${{ github.workspace }}/openwrt
           
    - name: Load custom feeds
      run: |
         [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
         chmod +x $DIY_P1_SH
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Upgrade golang for tailscale
      run: |
         cd openwrt
         rm -rf feeds/packages/lang/golang
         git clone --depth 1 -b 25.x https://github.com/sbwml/packages_lang_golang feeds/packages/lang/golang
      
    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
         [ -e files ] && mv files openwrt/files
         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
         cat ./doc/config/ua2f.config >> openwrt/.config
         chmod +x $DIY_P2_SH
         cd openwrt
         $GITHUB_WORKSPACE/$DIY_P2_SH
         if [ "$DEVICE" != "ALL" ]; then
           sed -i '/^CONFIG_TARGET_DEVICE_mediatek_mt7981_DEVICE_/d' .config
           sed -i '/^CONFIG_TARGET_DEVICE_PACKAGES_mediatek_mt7981_DEVICE_/d' .config
           echo "CONFIG_TARGET_DEVICE_mediatek_mt7981_DEVICE_${DEVICE}=y" >> .config
         fi
        
    - name: Download package
      id: package
      run: |
         cd openwrt
         make defconfig
         make download -j8
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
         make -j$(nproc) || make -j1 V=s
         echo "release_tag=${DEVICE}-k5.4-$(date +%Y.%m.%d)-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
         echo "release_name=${DEVICE}-OpenWrt-5.4" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && !cancelled()
      with:
         name: ${{ env.release_tag }}
         path: openwrt/bin

    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
         tar -cvf openwrt/bin/targets/mediatek/mt7981/packages.tar openwrt/bin/packages
         cd openwrt/bin/targets/mediatek/mt7981
         rm -rf packages
         rm -rf feeds.buildinfo
         rm -rf sha256sums
         rm -rf version.buildinfo
         rm -rf *kernel.bin
         rm -rf *manifest
         rm -rf *tar.bz2
         echo "FIRMWARE=$PWD" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
         name: ${{ env.release_name }}
         tag_name: ${{ env.release_tag }}
         body: |
             **Kernel**: 5.4
             **Gateway**: 192.168.50.1
             **Password**: password
             **Application**: homeproxy, tailscale, ttyd, ua2f
         files: ${{ env.FIRMWARE }}/*

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.3.3
      with:
        keep_latest: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
